"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { useStore } from "@/store/useStore";
import { translations, type TranslationKey } from "@/lib/i18n";
// Only types/default configuration belong in the browser; provider code is server-only.
type RecordData = Record<string, unknown> & { id?: string; name?: string; displayName?: string; number?: number; seasonId?: string };
type AdminData = { competitions: RecordData[]; seasons: RecordData[]; gameweeks: RecordData[]; teams: RecordData[]; players: RecordData[]; matches: RecordData[]; pickRules: RecordData[]; bonusQuestions: RecordData[]; achievements: RecordData[]; ai: RecordData[]; unmappedMatches: number; credentials: { football: boolean; ai: boolean }; leagues: RecordData[]; legacyTournaments: RecordData[] };
type Section = "competition" | "season" | "gameweek" | "match" | "team" | "player" | "pickRule" | "bonus" | "achievement";
const fieldClass = "w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm";
const buttonClass = "rounded-xl bg-emerald-600 px-4 py-3 text-sm font-black text-white disabled:opacity-40";
const references: Record<string, keyof AdminData> = { competitionId: "competitions", seasonId: "seasons", gameweekId: "gameweeks", teamId: "teams", homeTeamId: "teams", awayTeamId: "teams" };
function display(record: RecordData) { return String(record.name ?? record.displayName ?? record.text ?? record.key ?? record.number ?? record.id); }
export function AdminPlatform() {
  const { t, locale, setLocale } = useStore(); const [data, setData] = useState<AdminData | null>(null); const [seasonId, setSeasonId] = useState(""); const [section, setSection] = useState<Section>("season"); const [error, setError] = useState(""); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  const label = (key: string) => key in translations.en ? t(key as TranslationKey) : key.split(".").at(-1)!;
  const load = useCallback(async () => {
    try { const r = await fetch(`/api/admin/platform${seasonId ? `?seasonId=${seasonId}` : ""}`); const d = await r.json(); if (!r.ok) throw new Error(d.error); setData(d); setError(""); } catch (e) { setError(e instanceof Error ? e.message : ""); }
  }, [seasonId]);
  useEffect(() => { void load(); }, [load]);
  async function action(body: unknown) { setBusy(true); setError(""); setMessage(""); try { const r = await fetch("/api/admin/platform", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const d = await r.json(); if (!r.ok) throw new Error(d.error); setMessage(t("platform.saved")); await load(); } catch (e) { setError(e instanceof Error ? e.message : t("platform.error")); } finally { setBusy(false); } }
  const competitionId = String(data?.competitions[0]?.id ?? "");
  const defaults: Record<Section, Record<string, unknown>> = {
    competition: { name: "", shortName: "", slug: "", type: "LEAGUE", region: null, logoUrl: null, provider: "football-data", providerCode: null, isActive: true, displayPriority: 0 },
    season: { competitionId, displayName: "", startsAt: new Date().toISOString(), endsAt: null, providerSeason: new Date().getUTCFullYear(), usesGameweeks: true, isCurrent: false, status: "UPCOMING", timezone: "UTC", scoringRules: { outcome: 1, exact: 3, penalty: 0, legacyKnockout: false }, picksLockAt: null, picksLockGameweek: 3, underdogEnabled: false, underdogThreshold: 15, underdogPoints: 1, underdogMinSample: 20, aiConfig: { enabled: false, provider: "openai", model: "gpt-4o-mini", baseUrl: "https://api.openai.com/v1", timeoutMs: 15000, maxOutputTokens: 250 } },
    gameweek: { seasonId, number: 1, name: null, startsAt: null, endsAt: null }, team: { seasonId, name: "", shortName: null, badgeUrl: null }, player: { seasonId, teamId: null, name: "", position: null, isGoalkeeper: false },
    match: { seasonId, gameweekId: null, homeTeamId: "", awayTeamId: "", kickoffTime: new Date().toISOString(), status: "SCHEDULED", stage: "GROUP", homeScore: null, awayScore: null, isEnabled: true, clearOverride: false },
    pickRule: { seasonId, key: "champion", target: "TEAM", selectionCount: 1, points: 20, enabled: true, lockAt: null },
    bonus: { gameweekId: String(data?.gameweeks[0]?.id ?? ""), text: "", textMy: null, type: "SINGLE_CHOICE", options: [{ id: "yes", label: t("platform.homeWin"), labelMy: "အိမ်ရှင်နိုင်" }, { id: "no", label: t("platform.awayWin"), labelMy: "ဧည့်သည်နိုင်" }], points: 1, lockAt: new Date().toISOString(), isActive: true },
    achievement: { id: "", enabled: true, criteria: { scope: "season", metric: "exactScores", threshold: 10 } }
  };
  const collection: Record<Section, keyof AdminData> = { competition: "competitions", season: "seasons", gameweek: "gameweeks", match: "matches", team: "teams", player: "players", pickRule: "pickRules", bonus: "bonusQuestions", achievement: "achievements" };
  const sectionLabel = (s: Section) => s === "pickRule" ? t("platform.picks") : s === "achievement" ? t("platform.achievements") : label(`platform.field.${s === "competition" ? "competitionId" : s === "season" ? "seasonId" : s === "gameweek" ? "gameweekId" : s === "team" ? "teamId" : "name"}`);
  return <main className="mx-auto max-w-6xl space-y-5 p-5"><header className="flex flex-wrap items-center justify-between gap-3"><h1 className="text-3xl font-black text-navy">{t("platform.admin")}</h1><div className="flex gap-3"><select className={fieldClass} value={locale} onChange={e => setLocale(e.target.value as "en" | "my")}><option value="en">English</option><option value="my">မြန်မာ</option></select><Link href="/admin" className="whitespace-nowrap text-sm font-bold text-emerald-700">{t("platform.settings")}</Link></div></header>
    {error && <p role="alert" className="rounded-xl bg-red-50 p-4 text-sm text-red-700">{error} <Link href="/admin" className="font-bold underline">{t("platform.configure")}</Link></p>}{message && <p className="rounded-xl bg-emerald-50 p-3 text-sm font-bold text-emerald-700">{message}</p>}
    {data && <><section className="rounded-2xl bg-white p-5 shadow-sm"><p className="text-xs text-slate-500">{t("platform.credentials")}</p><p className="mt-2 text-sm">football-data.org {data.credentials.football ? "✓" : "—"} · AI {data.credentials.ai ? "✓" : "—"} · {t("platform.orphan")} {data.unmappedMatches}</p><select className={`${fieldClass} mt-3`} value={seasonId} onChange={e => setSeasonId(e.target.value)}><option value="">{t("platform.all")}</option>{data.seasons.map(s => <option key={s.id} value={s.id}>{display(s)} · {String((s.competition as Record<string, unknown>)?.name ?? "")}</option>)}</select><div className="mt-3 flex flex-wrap gap-2"><button disabled={busy} className={buttonClass} onClick={() => void action({ action: "bootstrap" })}>{t("platform.bootstrap")}</button>{seasonId && (["sync", "syncCatalog", "recalculate", "runAI"] as const).map(a => <button key={a} disabled={busy} className={buttonClass} onClick={() => void action({ action: a, seasonId })}>{t(`platform.${a}`)}</button>)}</div></section>
    <nav className="flex flex-wrap gap-2">{Object.keys(defaults).map(s => <button key={s} onClick={() => setSection(s as Section)} className={`rounded-xl px-4 py-3 text-sm font-bold ${section === s ? "bg-navy text-white" : "bg-white"}`}>{sectionLabel(s as Section)} · {s === "match" ? "⚽" : s === "player" ? "👤" : s === "bonus" ? "?" : ""}</button>)}</nav>
    <Editor key={`${section}:${seasonId}`} section={section} defaults={defaults[section]} rows={data[collection[section]] as RecordData[]} data={data} busy={busy} action={action} />
    {seasonId && <section className="grid gap-4 md:grid-cols-2"><div className="rounded-2xl bg-white p-5"><h2 className="font-black">{t("platform.picks")} · {t("platform.settle")}</h2>{data.pickRules.map(rule => <Settlement key={rule.id} rule={rule} data={data} busy={busy} action={action} />)}</div><div className="rounded-2xl bg-white p-5"><h2 className="font-black">{t("platform.bonus")} · {t("platform.settle")}</h2>{data.bonusQuestions.map(q => <form key={q.id} className="mt-3 space-y-2" onSubmit={e => { e.preventDefault(); const f = new FormData(e.currentTarget); void action({ action: "settleBonus", questionId: q.id, answer: String(f.get("answer")) }); }}><p className="text-sm font-bold">{String(q.text)}</p><select className={fieldClass} name="answer">{(q.options as { id: string; label: string; labelMy?: string }[]).map(o => <option key={o.id} value={o.id}>{locale === "my" && o.labelMy ? o.labelMy : o.label}</option>)}</select><button className={buttonClass} disabled={busy}>{t("platform.settle")}</button></form>)}</div></section>}
    <section className="rounded-2xl bg-white p-5"><h2 className="font-black">{t("platform.ai")}</h2>{data.ai.map(row => <div key={row.id} className="mt-2 flex flex-wrap items-center justify-between gap-2 rounded-xl bg-slate-50 p-3 text-sm"><span>#{String(row.matchId)} · {String(row.provider)} / {String(row.model)} · {String(row.status)}</span>{row.status !== "SUCCEEDED" && <button disabled={busy} className={buttonClass} onClick={() => void action({ action: "resetAI", seasonId: row.seasonId, matchId: row.matchId })}>{t("platform.resetAI")}</button>}</div>)}</section>
    <section className="rounded-2xl bg-white p-5"><h2 className="font-black">{t("platform.leagues")}</h2>{seasonId && <form className="mt-3 flex gap-2" onSubmit={e => { e.preventDefault(); void action({ action: "linkLeague", seasonId, leagueId: new FormData(e.currentTarget).get("leagueId") }); }}><select name="leagueId" className={fieldClass}>{data.leagues.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select><button className={buttonClass} disabled={busy}>{t("platform.linkSeason")}</button></form>}</section>
    <section className="rounded-2xl bg-white p-5"><h2 className="font-black">{t("platform.legacy")}</h2>{data.legacyTournaments.map(row => <button key={row.id} className={`${buttonClass} mr-2 mt-3`} disabled={busy} onClick={() => void action({ action: "backfill", tournamentId: row.id })}>{row.name} · {t("platform.configure")}</button>)}</section>
    </>}
  </main>;
}
function Editor({ section, defaults, rows, data, busy, action }: { section: Section; defaults: Record<string, unknown>; rows: RecordData[]; data: AdminData; busy: boolean; action: (body: unknown) => Promise<void> }) {
  const { t } = useStore(); const [id, setId] = useState(""); const [values, setValues] = useState(defaults); const [error, setError] = useState("");
  const enums: Record<string, string[]> = { status: section === "match" ? ["SCHEDULED", "LIVE", "PAUSED", "POSTPONED", "CANCELLED", "FINISHED"] : ["UPCOMING", "ACTIVE", "COMPLETED"], stage: ["GROUP", "ROUND_OF_32", "ROUND_OF_16", "QUARTER_FINAL", "SEMI_FINAL", "THIRD_PLACE", "FINAL"], type: section === "bonus" ? ["SINGLE_CHOICE", "BOOLEAN", "RANGE"] : ["LEAGUE", "KNOCKOUT", "HYBRID"], target: ["TEAM", "PLAYER"], provider: ["football-data", "legacy"] };
  const label = (key: string) => key in translations.en ? t(key as TranslationKey) : key.split(".").at(-1)!;
  function edit(next: string) { setId(next); const row = rows.find(r => String(r.id) === next); setValues(row ? Object.fromEntries(Object.keys(defaults).map(k => [k, row[k] ?? defaults[k]])) : defaults); }
  return <section className="rounded-2xl bg-white p-5 shadow-sm"><select className={`${fieldClass} mb-4`} value={id} onChange={e => edit(e.target.value)}><option value="">{t("platform.create")}</option>{rows.map(r => <option key={String(r.id)} value={String(r.id)}>{display(r)}{section === "match" ? ` · ${String(r.homeTeam)} – ${String(r.awayTeam)}` : ""}</option>)}</select><form className="grid gap-4 md:grid-cols-2" onSubmit={e => {
    e.preventDefault(); setError(""); try { const parsed = Object.fromEntries(Object.entries(values).map(([k, v]) => [k, ["scoringRules", "aiConfig", "options", "criteria"].includes(k) && typeof v === "string" ? JSON.parse(v) : v])); void action({ action: section, ...parsed, ...(id && section !== "pickRule" ? { id: section === "match" ? Number(id) : id } : {}) }); } catch { setError(t("platform.error")); }
  }}>{Object.entries(defaults).map(([key, initial]) => {
    const value = values[key]; const reference = references[key]; let choices = reference ? (data[reference] as RecordData[]) : [];
    if (["teamId", "homeTeamId", "awayTeamId", "gameweekId"].includes(key)) choices = choices.filter(c => c.seasonId === values.seasonId || section === "bonus");
    const nullable = initial === null; const numeric = typeof initial === "number" || ["homeScore", "awayScore", "picksLockGameweek", "providerSeason"].includes(key);
    return <label key={key} className="block text-xs font-bold text-slate-600"><span>{label(`platform.field.${key}`)}</span>{reference || enums[key] ? <select className={`${fieldClass} mt-1`} value={String(value ?? "")} onChange={e => setValues(old => ({ ...old, [key]: e.target.value || null }))}>{(nullable || reference) && <option value="">{t("platform.none")}</option>}{reference ? choices.map(c => <option key={String(c.id)} value={String(c.id)}>{display(c)}</option>) : enums[key].map(o => <option key={o} value={o}>{label(`platform.${o}`)}</option>)}</select> : typeof initial === "boolean" ? <input type="checkbox" className="ml-3 h-5 w-5" checked={Boolean(value)} onChange={e => setValues(old => ({ ...old, [key]: e.target.checked }))} /> : ["scoringRules", "aiConfig", "options", "criteria"].includes(key) ? <textarea rows={6} className={`${fieldClass} mt-1 font-mono`} value={typeof value === "string" ? value : JSON.stringify(value, null, 2)} onChange={e => setValues(old => ({ ...old, [key]: e.target.value }))} /> : <input type={numeric ? "number" : "text"} className={`${fieldClass} mt-1`} value={String(value ?? "")} onChange={e => setValues(old => ({ ...old, [key]: numeric ? e.target.value === "" ? null : Number(e.target.value) : nullable && e.target.value === "" ? null : e.target.value }))} />}</label>;
  })}{error && <p className="text-sm text-red-600">{error}</p>}<button className={`${buttonClass} md:col-span-2`} disabled={busy}>{t("platform.save")}</button></form></section>;
}
function Settlement({ rule, data, busy, action }: { rule: RecordData; data: AdminData; busy: boolean; action: (body: unknown) => Promise<void> }) {
  const { t } = useStore(); const key = `platform.pick.${String(rule.key)}`; const options = rule.target === "TEAM" ? data.teams : data.players.filter(p => rule.key === "goldenGlove" ? p.isGoalkeeper : rule.key === "goldenBoot" ? !p.isGoalkeeper : true);
  const [chosen, setChosen] = useState<string[]>((rule.settledSelections as string[]) ?? []);
  return <div className="mt-4 border-t border-slate-100 pt-3"><h3 className="text-sm font-bold">{key in translations.en ? t(key as TranslationKey) : String(rule.key)}</h3><div className="mt-2 max-h-40 overflow-y-auto">{options.map(o => <label key={o.id} className="flex justify-between py-2 text-sm">{o.name}<input type="checkbox" checked={chosen.includes(o.id!)} onChange={e => setChosen(old => e.target.checked ? [...old, o.id!] : old.filter(id => id !== o.id))} /></label>)}</div><button className={`${buttonClass} mt-2`} disabled={busy || chosen.length !== Number(rule.selectionCount)} onClick={() => void action({ action: "settlePick", ruleId: rule.id, selections: chosen })}>{t("platform.settle")}</button></div>;
}
