"use client";
import Link from "next/link";
import { useCallback, useEffect, useRef, useState } from "react";
import { SeasonDashboard, ClubBadge } from "./SeasonDashboard";
import { BallIcon, TrophyIcon, ArrowUpRightIcon, LockIcon } from "./Icons";
import { AppShell } from "./AppShell";
import { Card, SkeletonCard } from "./Cards";
import { PredictionForm } from "./PredictionForm";
import { LeagueActions } from "./LeagueActions";
import { useStore } from "@/store/useStore";
import { formatAppDateTime, formatAppDate } from "@/lib/dateTime";
import { platformAction, type ClientPlatformView, type ClientLeagueView } from "@/lib/platformClient";
import { translations, type TranslationKey } from "@/lib/i18n";
import type { revealMatch } from "@/services/platform/views";
import type { Serialized } from "@/lib/platformClient";
const button = "rounded-xl bg-[#123d2e] px-4 py-3 text-sm font-black text-white disabled:opacity-40";
const select = "w-full rounded-xl border border-slate-200 bg-white px-3 py-3 text-sm font-bold";
type Page = "home" | "predict" | "stats" | "profile" | "leagues" | "picks";
type Stats = { totalPredictions: number; correctPercent: number; exactPercent: number; bestGameweek: number; averageGameweek: number; bestRank: number; bankerPoints: number; bankerSuccess: number; bankerSamples: number; currentCorrect: number; bestCorrect: number; currentExact: number; bestExact: number; distribution: { HOME: number; DRAW: number; AWAY: number }; teamAccuracy: { name: string; accuracy: number; samples: number }[]; rankHistory: { number: number; rank: number; movement: number; points: number }[] };
function usePlatform() {
  const { user } = useStore(); const [view, setView] = useState<ClientPlatformView | null>(null); const [error, setError] = useState(""); const [loading, setLoading] = useState(true); const [gw, setGw] = useState(""); const enrolled = useRef(new Set<string>());
  const load = useCallback(async (resetGameweek = false) => {
    if (!user?.id) return;
    try {
      const response = await fetch(`/api/platform${gw && !resetGameweek ? `?gameweekId=${encodeURIComponent(gw)}` : ""}`, { cache: "no-store" }); const data = await response.json(); if (!response.ok) throw new Error(data.error);
      setView(data.view); setError(""); setLoading(false);
      if (data.view && !data.view.ownStanding && !enrolled.current.has(data.view.season.id)) { enrolled.current.add(data.view.season.id); await platformAction({ action: "enroll", seasonId: data.view.season.id }); const again = await fetch(`/api/platform${gw && !resetGameweek ? `?gameweekId=${encodeURIComponent(gw)}` : ""}`).then(r => r.json()); setView(again.view); }
    } catch (err) { setError(err instanceof Error ? err.message : ""); setLoading(false); }
  }, [gw, user?.id]);
  useEffect(() => { void load(); const timer = window.setInterval(() => void load(), 30000); return () => clearInterval(timer); }, [load]);
  useEffect(() => { const reset = () => { setGw(""); setView(null); setLoading(true); void load(true); }; window.addEventListener("football-context", reset); return () => window.removeEventListener("football-context", reset); }, [load]);
  return { view, error, loading, load, gw, setGw };
}
function NamedMetric({ label, value }: { label: string; value: React.ReactNode }) { return <div className="metric-tile"><p className="text-xs font-bold text-slate-500">{label}</p><p className="mt-2 text-3xl font-black tracking-tight text-[#123d2e]">{value}</p></div>; }
function RankList({ rows }: { rows: { user: { id: string; displayName: string; isSystem?: boolean }; rank: number; points?: number; totalPoints?: number; exactScores?: number; gameweekWins?: number }[] }) {
  const { t, user } = useStore();
  return <div className="space-y-1">{rows.length ? rows.map(row => <div key={row.user.id} className={`flex items-center gap-3 rounded-xl px-3 py-3 ${row.user.id === user?.id ? "bg-[#edf4e5] ring-1 ring-[#d8e5c8]" : "border-b border-slate-100"}`}><span className={`w-5 text-sm font-black ${row.rank === 1 ? "text-amber-600" : "text-slate-400"}`}>{row.rank || "—"}</span><span aria-hidden="true" className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#e7ece3] text-xs font-black text-[#40614b]">{row.user.displayName.slice(0, 2).toUpperCase()}</span><div className="min-w-0 flex-1"><p className="truncate text-sm font-bold">{row.user.displayName}{row.user.id === user?.id && <span className="ml-2 text-[9px] text-emerald-700">{t("ui.you")}</span>}</p>{typeof row.exactScores === "number" && <p className="mt-0.5 text-[10px] text-slate-500">{row.exactScores} {t("platform.exact")}</p>}</div><span className="text-lg font-black tabular-nums text-[#123d2e]">{row.points ?? row.totalPoints ?? 0}<span className="ml-1 text-[10px] font-bold text-slate-500">{t("common.pointsShort")}</span></span></div>) : <p className="py-6 text-center text-xs text-slate-500">{t("platform.empty")}</p>}</div>;
}
function localizedEntity(key: string, t: ReturnType<typeof useStore>["t"]) { return key in translations.en ? t(key as TranslationKey) : key.split(".").at(-1)!; }
export function PlatformScreen({ page, leagueId }: { page: Page; leagueId?: string }) {
  const { t } = useStore(); const { view, error, loading, load, setGw } = usePlatform(); const [busy, setBusy] = useState(false); const [actionError, setActionError] = useState(""); const [filter, setFilter] = useState("all");
  const selectedWeekButton = useRef<HTMLButtonElement | null>(null);
  useEffect(() => { selectedWeekButton.current?.scrollIntoView({ block: "nearest", inline: "center" }); }, [view?.currentGameweek?.id]);
  async function act(body: unknown) { setBusy(true); setActionError(""); try { await platformAction(body); await load(); } catch (err) { setActionError(err instanceof Error ? err.message : t("platform.error")); } finally { setBusy(false); } }
  if (loading) return <AppShell title={t("platform.title")}><SkeletonCard /><SkeletonCard /></AppShell>;
  if (!view) return <AppShell title={t("platform.title")}><Card><p>{error || t("platform.noSeason")}</p><button className={`${button} mt-3`} onClick={() => void load()}>{t("platform.refresh")}</button></Card></AppShell>;
  const own = view.ownStanding, week = view.currentGameweek, stats = (own?.stats ?? {}) as unknown as Partial<Stats>;
  const filteredMatches = view.matches.filter(match => filter === "all" || filter === "remaining" && !match.prediction && !match.isLocked || filter === "saved" && Boolean(match.prediction) || filter === "live" && ["LIVE", "PAUSED"].includes(match.status));
  const ownHistory = stats.rankHistory ?? []; const movement = ownHistory.at(-1)?.movement ?? 0;
  const pageTitle = page === "home" ? t("platform.title") : t(`platform.${page === "predict" ? "predictions" : page}`);
  return <AppShell title={pageTitle} eyebrow={`${view.season.competition.name} · ${view.season.displayName}`}>
    {(error || actionError) && <Card><p role="alert" className="text-sm text-red-600">{error || actionError}</p></Card>}
    {view.gameweeks.length > 0 && <div className="gameweek-toolbar"><div className="flex items-center justify-between gap-3"><p className="section-kicker">{t("platform.gameweek")}</p><span className="text-xs font-bold text-slate-400">{week?.number ?? "—"} / {view.gameweeks.length}</span></div><div className="gameweek-strip" role="group" aria-label={t("platform.gameweek")}>{view.gameweeks.map(g => <button ref={g.id === week?.id ? selectedWeekButton : undefined} key={g.id} aria-pressed={g.id === week?.id} aria-label={`${t("platform.gameweek")} ${g.number}${g.finalized ? ` · ${t("platform.complete")}` : ""}`} onClick={() => setGw(g.id)}>{g.number}{g.finalized && <span className="ml-1 text-[9px]" aria-hidden="true">✓</span>}</button>)}</div></div>}
    {page === "home" && <>
      <SeasonDashboard view={view} />
      <div className="home-metrics grid grid-cols-2 gap-3"><NamedMetric label={t("platform.thisWeek")} value={view.ownGameweek?.points ?? 0} /><NamedMetric label={t("platform.rank")} value={own?.rank ? `#${own.rank}` : "—"} /><NamedMetric label={t("ui.seasonPoints")} value={own?.totalPoints ?? 0} /><NamedMetric label={t("platform.movement")} value={`${movement > 0 ? "↑" : movement < 0 ? "↓" : "—"} ${Math.abs(movement) || ""}`} /></div>
      <div className="season-social-grid"><RivalCard view={view} act={act} busy={busy} />
      <Standings view={view} />
      <Hall view={view} />
      <Card><h2 className="font-black">{t("platform.achievements")}</h2><Achievements view={view} /></Card></div>
      {view.season.legacyTournamentId && <Link href="/tournament-view" className="block text-center text-sm font-bold text-emerald-700">{t("platform.legacy")}</Link>}
    </>}
    {page === "predict" && <>
      <div className="predict-progress"><div className="flex items-center justify-between gap-3"><div><p className="text-sm font-black">{view.progress.complete} / {view.progress.total} {t("platform.complete")}</p><p className="mt-1 text-[11px] text-slate-500">{t("ui.pickScore")}</p></div><span className="score-chip">{t("platform.banker")}</span></div><progress aria-label={t("platform.predictions")} className="mt-3 h-1.5 w-full" value={view.progress.complete} max={Math.max(1, view.progress.total)} /><div className="prediction-filters" role="group" aria-label={t("ui.filterMatches")}>{(["all", "remaining", "saved", "live"] as const).map(value => <button key={value} aria-pressed={filter === value} onClick={() => setFilter(value)}>{t(`ui.filter.${value}`)}</button>)}</div></div>
      {!filteredMatches.length && <Card><div className="season-empty"><BallIcon className="h-8 w-8 text-emerald-700" /><h3>{view.matches.length ? t("ui.noFilteredMatches") : t("ui.fixturesComing")}</h3><p>{view.matches.length ? t("ui.changeFilter") : t("platform.noFixtures")}</p></div></Card>}
      {filteredMatches.map((m, index) => <div key={m.id} className="predict-match">
        {(index === 0 || formatAppDate(filteredMatches[index - 1].kickoffTime) !== formatAppDate(m.kickoffTime)) && <h2 className="my-4 text-xs font-black uppercase tracking-wide text-slate-500">{formatAppDate(m.kickoffTime, { weekday: "long", day: "numeric", month: "short" })}</h2>}
        <Card className={`match-card ${m.isBanker ? "is-banker" : ""} ${["LIVE", "PAUSED"].includes(m.status) ? "is-live" : ""}`}><details open={!m.prediction && !m.isLocked}><summary className="cursor-pointer list-none"><div className="flex justify-between text-xs font-bold text-slate-500"><span>{formatAppDateTime(m.kickoffTime)}</span><span className="flex items-center gap-1">{localizedEntity(`platform.${m.status}`, t)} {m.isLocked && <LockIcon className="h-3 w-3" />}</span></div><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-start gap-3"><div className="flex flex-col items-center gap-2 text-center"><ClubBadge name={m.homeTeam} image={m.homeFlagImageUrl} /><h3 className="text-sm font-black">{m.homeTeam}</h3></div><span className="pt-2 text-xs font-semibold text-slate-400">{t("ui.versus")}</span><div className="flex flex-col items-center gap-2 text-center"><ClubBadge name={m.awayTeam} image={m.awayFlagImageUrl} /><h3 className="text-sm font-black">{m.awayTeam}</h3></div></div><div className="prediction-summary"><span className="text-xs font-semibold text-slate-500">{m.prediction ? t("ui.yourPrediction") : t("predict.tapToPick")}</span>{m.isBanker && <span className="rounded-full bg-amber-100 px-2 py-1 text-[10px] font-black text-amber-800">×2</span>}<span className="score-chip">{m.prediction ? `${m.prediction.predictedHomeScore} : ${m.prediction.predictedAwayScore}` : "+"}</span><span aria-hidden="true" className="text-slate-400">⌄</span></div></summary>
          <PredictionForm match={m} serverNowIso={view.serverNow} onSaved={() => void load()} />
        </details>
        {week && <button className="mt-3 w-full rounded-xl bg-amber-50 px-3 py-2 text-xs font-black text-amber-800 disabled:opacity-40" disabled={busy || m.isLocked || !m.prediction} onClick={() => void act({ action: "banker", gameweekId: week.id, matchId: m.isBanker ? null : m.id })}>{m.isBanker ? t("platform.removeBanker") : m.isLocked ? t("platform.locked") : !m.prediction ? t("platform.saveFirst") : t("platform.chooseBanker")}</button>}
        {m.status !== "SCHEDULED" && <p className="mt-3 text-sm font-bold">{localizedEntity(`platform.${m.status}`, t)} · {m.homeScore ?? "—"}–{m.awayScore ?? "—"}</p>}
        {m.provisionalPoints !== null && <p className="mt-2 rounded-xl bg-cyan-50 p-2 text-xs font-bold text-cyan-800">{t("platform.provisional")} · {m.provisionalPoints}</p>}
        {m.prediction?.pointsAwarded != null && <p className="mt-2 text-xs font-bold text-emerald-700">{t("platform.final")} · {m.prediction.basePoints} ×{m.prediction.pointsMultiplier} {m.prediction.upsetPoints ? `+${m.prediction.upsetPoints}` : ""} = {m.prediction.pointsAwarded}</p>}
        <MatchCommunity matchId={m.id} hasPrediction={Boolean(m.prediction)} leagues={view.leagues.filter(l => l.seasons.length > 0)} />
        </Card>
      </div>)}
      {view.bonusQuestions.map(q => <BonusForm key={q.id} question={q} act={act} busy={busy} />)}
    </>}
    {page === "stats" && <>
      <StatsPanel view={view} />
      <Standings view={view} />
      <Card><h2 className="font-black">{t("platform.ai")}</h2>{view.ai.enabled ? <div className="mt-3 grid grid-cols-2 gap-2"><NamedMetric label={t("platform.humanWins")} value={view.ai.humanGameweekWins} /><NamedMetric label={t("platform.aiWins")} value={view.ai.aiGameweekWins} /><NamedMetric label={t("platform.aiRank")} value={view.ai.rank ? `#${view.ai.rank}` : "—"} /></div> : <p className="mt-2 text-sm text-slate-500">{t("platform.aiDisabled")}</p>}</Card>
      <Hall view={view} />
    </>}
    {page === "profile" && <>
      <Card><div className="flex items-center gap-3">{view.user.avatarUrl && <img src={view.user.avatarUrl} alt="" className="h-12 w-12 rounded-full" />}<h2 className="text-2xl font-black">{view.user.displayName}</h2></div><div className="mt-4 grid grid-cols-2 gap-2 md:grid-cols-4"><NamedMetric label={t("platform.rank")} value={own?.rank ? `#${own.rank}` : "—"} /><NamedMetric label={t("platform.season")} value={own?.totalPoints ?? 0} /><NamedMetric label={t("platform.wins")} value={own?.gameweekWins ?? 0} /><NamedMetric label={t("platform.exact")} value={own?.exactScores ?? 0} /></div></Card>
      <RivalCard view={view} act={act} busy={busy} />
      <Card><h2 className="font-black">{t("platform.achievements")}</h2><Achievements view={view} /></Card>
      <StatsPanel view={view} />
      <Card><h2 className="mb-3 font-black">{t("platform.history")}</h2>{view.history.map(h => <button key={h.seasonId} className="mb-2 block w-full rounded-xl bg-slate-50 p-3 text-left text-sm font-bold" onClick={() => void act({ action: "context", seasonId: h.seasonId }).then(() => window.dispatchEvent(new Event("football-context")))}>{h.season.competition.name} {h.season.displayName}<span className="mt-1 block text-xs text-slate-500">#{h.rank || "—"} · {h.totalPoints} {t("common.pointsShort")}</span></button>)}</Card>
      <NotificationList view={view} act={act} />
      <Card><h2 className="font-black">{t("platform.preferences")}</h2>{(["all", "reminders", "gameweek", "rival", "achievement"] as const).map(key => <label key={key} className="mt-3 flex justify-between text-sm font-bold">{localizedEntity(key === "all" ? "platform.all" : key === "reminders" ? "platform.reminders" : `platform.notification.${key}`, t)}<input type="checkbox" checked={(view.user.notificationSettings as Record<string, boolean>)[key] !== false} disabled={busy} onChange={e => void act({ action: "notificationPreferences", all: true, reminders: true, gameweek: true, rival: true, achievement: true, ...(view.user.notificationSettings as object), [key]: e.target.checked })} /></label>)}</Card>
      <Link href="/history" className="block text-center text-sm font-bold text-emerald-700">{t("nav.history")}</Link>
    </>}
    {page === "picks" && <>
      <Card><p className="text-sm text-slate-600">{t("platform.picksHelp")}</p></Card>
      {view.pickRules.filter(r => r.enabled).map(rule => <PickForm key={rule.id} rule={rule} view={view} act={act} busy={busy} />)}
      {view.season.legacyTournamentId && <Link href="/winners" className={`${button} block text-center`}>{t("platform.legacy")}</Link>}
    </>}
    {page === "leagues" && <>
      {!leagueId && <LeagueActions onChanged={load} />}
      {leagueId ? <LeagueView leagueId={leagueId} view={view} act={act} busy={busy} /> : view.leagues.map(l => <Card key={l.id}><Link href={`/leagues/${l.id}`} className="flex items-center justify-between gap-3"><span className="flex h-11 w-11 shrink-0 items-center justify-center rounded-xl bg-emerald-50 text-emerald-800"><TrophyIcon className="h-5 w-5" /></span><span className="flex-1 font-black">{l.name}<span className="mt-1 block text-xs font-medium text-slate-500">{view.season.displayName}</span></span><ArrowUpRightIcon className="h-5 w-5 text-emerald-700" /></Link>{!l.seasons.length && l.ownerUserId === view.user.id && <button className={`${button} mt-3 block`} disabled={busy} onClick={() => void act({ action: "linkLeague", leagueId: l.id, seasonId: view.season.id })}>{t("platform.linkSeason")}</button>}</Card>)}
    </>}
  </AppShell>;
}
function RivalCard({ view, act, busy }: { view: ClientPlatformView; act: (body: unknown) => Promise<void>; busy: boolean }) {
  const { t } = useStore(); const difference = (view.ownStanding?.totalPoints ?? 0) - (view.rival?.standing?.totalPoints ?? 0);
  return <Card><p className="section-kicker">{t("ui.seasonSocial")}</p><h2 className="mt-1 text-lg font-black">{t("platform.rival")}</h2>{view.rival && <><div className="mt-5 grid grid-cols-[1fr_auto_1fr] items-center gap-3"><div className="rounded-2xl bg-[#edf4e5] p-4 text-center"><p className="text-xs font-bold text-emerald-800">{t("platform.you")}</p><p className="mt-2 text-3xl font-black tabular-nums text-[#123d2e]">{view.ownStanding?.totalPoints ?? 0}</p><p className="mt-1 text-[10px] text-slate-500">#{view.ownStanding?.rank ?? "—"}</p></div><span className="text-[10px] font-black text-slate-400">{t("ui.versus")}</span><div className="rounded-2xl bg-slate-50 p-4 text-center"><p className="truncate text-xs font-bold">{view.rival.user.displayName}</p><p className="mt-2 text-3xl font-black tabular-nums">{view.rival.standing?.totalPoints ?? 0}</p><p className="mt-1 text-[10px] text-slate-500">#{view.rival.standing?.rank ?? "—"}</p></div></div><p className="mt-4 text-center text-xs font-bold text-emerald-800">{difference >= 0 ? t("platform.ahead") : t("platform.behind")} · {Math.abs(difference)}</p><p className="mt-2 text-center text-[11px] text-slate-500">{t("platform.thisWeek")} · {view.ownGameweek?.points ?? 0} – {view.rival.gameweekPoints}</p></>}<select className={`${select} mt-4`} aria-label={t("platform.selectRival")} value={view.rival?.user.id ?? ""} disabled={busy} onChange={e => void act({ action: "rival", seasonId: view.season.id, rivalId: e.target.value || null })}><option value="">{t("platform.selectRival")}</option>{view.eligibleRivals.map(r => <option key={r.id} value={r.id}>{r.displayName}</option>)}</select></Card>;
}
function Hall({ view }: { view: ClientPlatformView }) { const { t } = useStore(); return <Card><div className="mb-4 flex items-center gap-3"><TrophyIcon className="h-6 w-6 text-amber-600" /><h2 className="font-black">{t("platform.hall")}</h2></div>{!view.hallOfFame.length && <p className="text-xs leading-relaxed text-slate-500">{t("ui.championsComing")}</p>}{view.hallOfFame.map(row => <p key={row.gameweekId} className="flex justify-between border-b border-slate-100 py-2 text-sm"><span>{t("platform.gameweek")} {row.gameweek.number} · {row.user.displayName}</span><strong>{row.points} {t("common.pointsShort")}</strong></p>)}{view.currentGameweek?.finalized && view.gameweekStandings[0] && <p className="mt-3 rounded-xl bg-amber-50 p-3 text-sm font-black text-amber-800">{t("platform.champion")} · {view.gameweekStandings[0].user.displayName}</p>}</Card>; }
function Achievements({ view }: { view: ClientPlatformView }) { const { t } = useStore(); return <div className="mt-3 flex flex-wrap gap-2">{view.achievements.map(a => <span key={a.id} className="rounded-xl bg-amber-50 px-3 py-2 text-xs font-bold text-amber-800">{localizedEntity(`platform.${a.definitionId}`, t)}</span>)}{!view.achievements.length && <p className="text-sm text-slate-500">{t("platform.empty")}</p>}</div>; }
function Standings({ view }: { view: ClientPlatformView }) {
  const { t } = useStore(); const [tab, setTab] = useState("season"); const [metric, setMetric] = useState("correct");
  const eligible = view.standings.filter(s => metric === "banker" ? Number((s.stats as Record<string, unknown>).bankerSamples ?? 0) >= 5 : s.predictionCount >= 10).map(s => ({ ...s, rate: metric === "banker" ? Number((s.stats as Record<string, unknown>).bankerSuccess ?? 0) : (metric === "exact" ? s.exactScores : s.correctOutcomes) * 100 / s.predictionCount })).sort((a, b) => b.rate - a.rate || a.rank - b.rank);
  return <Card><p className="section-kicker mb-3">{t("ui.rankings")}</p><div className="mb-3 flex flex-wrap gap-2">{(["season", "week", "accuracy"] as const).map(value => <button key={value} aria-pressed={tab === value} onClick={() => setTab(value)} className={`rounded-xl px-3 py-2 text-xs font-black ${tab === value ? "bg-[#123d2e] text-white" : "bg-slate-100"}`}>{t(value === "season" ? "platform.seasonTable" : value === "week" ? "platform.weekTable" : "platform.accuracyTable")}</button>)}</div>{tab === "season" ? <RankList rows={view.standings} /> : tab === "week" ? <><RankList rows={view.gameweekStandings} />{view.matches.some(m => m.provisionalPoints !== null) && <div className="mt-3"><p className="mb-2 text-xs font-black text-cyan-700">{t("platform.provisional")}</p>{view.liveLeaderboard.map(row => <p key={row.user.id} className="flex justify-between py-1 text-sm"><span>{row.user.displayName}</span><span>{row.finalPoints} + {row.provisionalPoints}</span></p>)}</div>}</> : <><select className={`${select} mb-3`} value={metric} onChange={e => setMetric(e.target.value)}><option value="correct">{t("platform.correct")}</option><option value="exact">{t("platform.exact")}</option><option value="banker">{t("platform.bankerSuccess")}</option></select>{eligible.map((r, i) => <p key={r.userId} className="flex justify-between py-2 text-sm"><span>#{i + 1} {r.user.displayName}</span><strong>{r.rate.toFixed(1)}%</strong></p>)}</>}</Card>;
}
function StatsPanel({ view }: { view: ClientPlatformView }) {
  const { t } = useStore(); const stats = (view.ownStanding?.stats ?? {}) as unknown as Partial<Stats>; const own = view.ownStanding;
  const metrics: [TranslationKey, number | string][] = [["platform.totalPredictions", stats.totalPredictions ?? 0], ["platform.correct", `${own?.correctOutcomes ?? 0} (${(stats.correctPercent ?? 0).toFixed(1)}%)`], ["platform.exact", `${own?.exactScores ?? 0} (${(stats.exactPercent ?? 0).toFixed(1)}%)`], ["platform.wins", own?.gameweekWins ?? 0], ["platform.bestWeek", stats.bestGameweek ?? 0], ["platform.averageWeek", (stats.averageGameweek ?? 0).toFixed(1)], ["platform.bestRank", stats.bestRank ? `#${stats.bestRank}` : "—"], ["platform.bankerPoints", stats.bankerPoints ?? 0], ["platform.bankerSuccess", `${(stats.bankerSuccess ?? 0).toFixed(1)}%`], ["platform.currentCorrect", stats.currentCorrect ?? 0], ["platform.bestCorrect", stats.bestCorrect ?? 0], ["platform.currentExact", stats.currentExact ?? 0], ["platform.bestExact", stats.bestExact ?? 0]];
  const history = stats.rankHistory ?? []; const max = Math.max(1, ...history.map(h => h.rank)); const line = history.map((h, i) => `${history.length > 1 ? i * 280 / (history.length - 1) + 10 : 10},${10 + (h.rank - 1) * 80 / max}`).join(" ");
  return <><Card><h2 className="mb-3 font-black">{t("platform.stats")}</h2><div className="grid grid-cols-2 gap-2 md:grid-cols-4">{metrics.map(([label, value]) => <NamedMetric key={label} label={t(label)} value={value} />)}</div></Card><Card><h2 className="font-black">{t("platform.distribution")}</h2>{(["HOME", "DRAW", "AWAY"] as const).map(key => <div key={key} className="mt-3 text-sm"><p className="flex justify-between"><span>{t(key === "HOME" ? "platform.homeWin" : key === "DRAW" ? "platform.draw" : "platform.awayWin")}</span><strong>{stats.totalPredictions ? ((stats.distribution?.[key] ?? 0) * 100 / stats.totalPredictions).toFixed(1) : 0}%</strong></p><progress className="mt-1 h-2 w-full accent-emerald-600" value={stats.distribution?.[key] ?? 0} max={stats.totalPredictions || 1} /></div>)}</Card><Card><h2 className="font-black">{t("platform.teamAccuracy")}</h2><p className="mt-2 text-xs text-slate-500">{t("platform.bestTeam")} · {stats.teamAccuracy?.[0]?.name ?? "—"}</p><p className="mt-1 text-xs text-slate-500">{t("platform.worstTeam")} · {stats.teamAccuracy?.at(-1)?.name ?? "—"}</p>{stats.teamAccuracy?.map(team => <p key={team.name} className="mt-2 flex justify-between text-sm"><span>{team.name}</span><strong>{team.accuracy}% · {team.samples}</strong></p>)}</Card><Card><h2 className="font-black">{t("platform.rankHistory")}</h2>{history.length > 0 && <svg viewBox="0 0 300 110" role="img" aria-label={t("platform.rankHistory")} className="mt-3 w-full"><polyline points={line} fill="none" stroke="#059669" strokeWidth="3" />{history.map((h, i) => <circle key={h.number} cx={history.length > 1 ? i * 280 / (history.length - 1) + 10 : 10} cy={10 + (h.rank - 1) * 80 / max} r="3" fill="#059669"><title>{t("platform.gameweek")} {h.number}: #{h.rank}</title></circle>)}</svg>}<div className="max-h-40 overflow-y-auto">{history.map(h => <p key={h.number} className="mt-2 flex justify-between text-xs"><span>{t("platform.gameweek")} {h.number}</span><strong>#{h.rank} · {h.points} {t("common.pointsShort")}</strong></p>)}</div></Card></>;
}
function PickForm({ rule, view, act, busy }: { rule: ClientPlatformView["pickRules"][number]; view: ClientPlatformView; act: (body: unknown) => Promise<void>; busy: boolean }) {
  const { t } = useStore(); const [chosen, setChosen] = useState(rule.own?.selections ?? []); useEffect(() => setChosen(rule.own?.selections ?? []), [rule.own?.selections]);
  const options = rule.target === "TEAM" ? view.teams : view.players.filter(p => rule.key === "goldenGlove" ? p.isGoalkeeper : rule.key === "goldenBoot" ? !p.isGoalkeeper : true); const locked = rule.settled || view.season.status === "COMPLETED" || view.serverNow >= rule.lockAt;
  return <Card><h2 className="font-black">{localizedEntity(`platform.pick.${rule.key}`, t)}</h2><p className="mt-1 text-xs text-slate-500">{rule.points} {t("common.pointsShort")} · {chosen.length}/{rule.selectionCount} · {t("platform.lockTime")} {formatAppDateTime(rule.lockAt)}</p><div className="mt-3 max-h-64 space-y-2 overflow-y-auto">{options.map(option => <label key={option.id} className="flex items-center justify-between rounded-xl bg-slate-50 p-3 text-sm font-bold"><span>{option.name}</span><input type="checkbox" checked={chosen.includes(option.id)} disabled={locked || busy || !chosen.includes(option.id) && chosen.length >= rule.selectionCount} onChange={e => setChosen(old => e.target.checked ? [...old, option.id] : old.filter(id => id !== option.id))} /></label>)}</div><button className={`${button} mt-3 w-full`} disabled={locked || busy || chosen.length !== rule.selectionCount} onClick={() => void act({ action: "pick", ruleId: rule.id, selections: chosen })}>{locked ? t("platform.locked") : t("platform.save")}</button>{rule.own?.pointsAwarded != null && <p className="mt-2 text-xs font-bold">{t("platform.final")} · {rule.own.pointsAwarded}</p>}</Card>;
}
function BonusForm({ question: q, act, busy }: { question: ClientPlatformView["bonusQuestions"][number]; act: (body: unknown) => Promise<void>; busy: boolean }) {
  const { t, locale } = useStore(); const [answer, setAnswer] = useState(q.own?.answer ?? "");
  return <Card><p className="text-xs font-bold text-emerald-600">{t("platform.bonus")} · {q.points} {t("common.pointsShort")}</p><h3 className="mt-2 font-black">{locale === "my" && q.textMy ? q.textMy : q.text}</h3><p className="mt-2 text-xs text-slate-500">{t("platform.lockTime")} {formatAppDateTime(q.lockAt)}</p><select className={`${select} mt-3`} value={answer} disabled={q.locked || busy} onChange={e => setAnswer(e.target.value)}><option value="">{t("platform.none")}</option>{q.options.map(o => <option key={o.id} value={o.id}>{locale === "my" && o.labelMy ? o.labelMy : o.label}</option>)}</select><button className={`${button} mt-3 w-full`} disabled={q.locked || busy || !answer} onClick={() => void act({ action: "bonus", questionId: q.id, answer })}>{q.locked ? t("platform.locked") : t("platform.save")}</button>{q.own?.pointsAwarded != null && <p className="mt-2 text-xs font-bold">{t("platform.bonusPoints")} · {q.own.pointsAwarded}</p>}</Card>;
}
function MatchCommunity({ matchId, hasPrediction, leagues }: { matchId: number; hasPrediction: boolean; leagues: ClientPlatformView["leagues"] }) {
  const { t } = useStore(); const [data, setData] = useState<Serialized<Awaited<ReturnType<typeof revealMatch>>> | null>(null); const [league, setLeague] = useState(""); const [open, setOpen] = useState(false);
  useEffect(() => { if (!open) return; let active = true; fetch(`/api/platform/matches/${matchId}${league ? `?leagueId=${league}` : ""}`).then(r => r.ok ? r.json() : null).then(d => { if (active) setData(d); }).catch(() => {}); return () => { active = false; }; }, [open, matchId, league, hasPrediction]);
  return <div className="mt-3 border-t border-slate-100 pt-3"><button onClick={() => setOpen(!open)} className="text-xs font-black text-indigo-700">{t("platform.viewConsensus")}</button>{open && <div className="mt-3 space-y-2">{!hasPrediction && <p className="text-xs text-slate-500">{t("platform.communityHelp")}</p>}{data?.community && <div className="rounded-xl bg-indigo-50 p-3 text-xs"><p className="font-black">{t("platform.community")} · {data.community.predictionCount}</p><p className="mt-2">{t("platform.homeWin")} {data.community.homePercent.toFixed(0)}% · {t("platform.draw")} {data.community.drawPercent.toFixed(0)}% · {t("platform.awayWin")} {data.community.awayPercent.toFixed(0)}%</p><p className="mt-1">{t("platform.averageScore")} · {data.community.averageHome.toFixed(1)} – {data.community.averageAway.toFixed(1)}</p></div>}<select className={select} value={league} onChange={e => setLeague(e.target.value)}><option value="">{t("platform.you")}</option>{leagues.map(l => <option key={l.id} value={l.id}>{l.name}</option>)}</select>{data?.hidden ? <p className="text-xs font-bold text-slate-500">{t("platform.hidden")}</p> : data?.predictions.map(p => <p key={p.user.id} className="flex justify-between text-sm"><span>{p.user.displayName}</span><strong>{p.predictedHomeScore}–{p.predictedAwayScore}</strong></p>)}</div>}</div>;
}
function NotificationList({ view, act }: { view: ClientPlatformView; act: (body: unknown) => Promise<void> }) {
  const { t } = useStore(); return <Card><h2 className="font-black">{t("platform.notifications")}</h2>{view.notifications.map(n => { const p = n.params as Record<string, string | number>; return <div key={n.id} className={`mt-3 rounded-xl p-3 text-xs ${n.readAt ? "bg-slate-50" : "bg-emerald-50"}`}><p className="font-black">{localizedEntity(`platform.notification.${n.type}`, t)}</p><p className="mt-1">{p.home ? `${p.home} – ${p.away}` : p.definitionId ? localizedEntity(`platform.${p.definitionId}`, t) : p.name ?? `${t("platform.gameweek")} ${p.number ?? ""}`}{p.rank ? ` · #${p.rank}` : ""}{p.points != null ? ` · ${p.points} ${t("common.pointsShort")}` : ""}{p.missing ? ` · ${p.missing} ${t("platform.predictions")}` : ""}{p.difference != null ? ` · ${Number(p.difference) >= 0 ? "+" : ""}${p.difference}` : ""}</p>{!n.readAt && <button className="mt-2 font-bold text-emerald-700" onClick={() => void act({ action: "readNotification", id: n.id })}>{t("platform.markRead")}</button>}</div>; })}</Card>;
}
function LeagueView({ leagueId, view, act, busy }: { leagueId: string; view: ClientPlatformView; act: (body: unknown) => Promise<void>; busy: boolean }) {
  const { t } = useStore(); const [data, setData] = useState<ClientLeagueView | null>(null); const [error, setError] = useState(""); const [tab, setTab] = useState("overall");
  useEffect(() => { let active = true; fetch(`/api/platform/league/${leagueId}?seasonId=${view.season.id}${view.currentGameweek ? `&gameweekId=${view.currentGameweek.id}` : ""}`).then(async r => { const d = await r.json(); if (!r.ok) throw new Error(d.error); if (active) { setData(d.view); setError(""); } }).catch(e => { if (active) setError(e.message); }); return () => { active = false; }; }, [leagueId, view]);
  if (error) return <Card>{error}</Card>; if (!data) return <SkeletonCard />;
  return <><Card><h2 className="text-xl font-black">{data.league.name}</h2><p className="mt-2 text-xs font-bold">{t("platform.joinCode")} · {data.league.joinCode}</p>{!data.link && data.league.ownerUserId === view.user.id && <button className={`${button} mt-3`} disabled={busy} onClick={() => void act({ action: "linkLeague", leagueId, seasonId: view.season.id })}>{t("platform.linkSeason")}</button>}<div className="mt-3 flex gap-2">{["overall", "gameweek", "h2h"].map(value => <button key={value} className={`rounded-xl px-3 py-2 text-xs font-black ${tab === value ? "bg-[#123d2e] text-white" : "bg-slate-100"}`} onClick={() => setTab(value)}>{t(`platform.${value}` as TranslationKey)}</button>)}</div></Card>{tab !== "h2h" ? <Card>{(tab === "gameweek" ? data.gameweekLeaderboard ?? [] : data.leaderboard).map(row => <div key={row.userId} className="flex items-center justify-between border-b border-slate-100 py-3 text-sm"><span>#{row.rank} {row.user.displayName}</span><strong>{row.gameweekPoints} / {row.points}</strong><span className="text-xs">{row.movement > 0 ? "↑" : row.movement < 0 ? "↓" : "—"}{Math.abs(row.movement) || ""}</span></div>)}</Card> : <><Card><p className="text-xs text-slate-500">{t("platform.h2hHelp")}</p>{!data.link?.lockedAt && data.league.ownerUserId === view.user.id && <button className={`${button} mt-3`} disabled={busy} onClick={() => void act({ action: "h2h", seasonId: view.season.id, leagueId })}>{t("platform.generateH2H")}</button>}{data.h2h.map((row, i) => <div key={row.user.id} className="mt-3 rounded-xl bg-slate-50 p-3 text-sm"><p className="flex justify-between font-black"><span>#{i + 1} {row.user.displayName}</span><span>{row.points} {t("common.pointsShort")}</span></p><p className="mt-1 text-xs">{t("platform.played")} {row.played} · {t("platform.won")} {row.wins} · {t("platform.drawn")} {row.draws} · {t("platform.lost")} {row.losses}</p><p className="mt-1 text-xs">{t("platform.for")} {row.for} · {t("platform.against")} {row.against}</p></div>)}</Card>{data.fixtures.map(f => <Card key={f.id}><p className="text-xs text-slate-500">{t("platform.gameweek")} {f.gameweek.number}</p><p className="mt-2 flex justify-between font-bold"><span>{f.homeUser.displayName} · {f.homePoints ?? "—"}</span><span>{f.awayUser?.displayName ?? t("platform.bye")} · {f.awayPoints ?? "—"}</span></p></Card>)}</>}</>;
}
